### ISSUE TITLE
ERROR executing register_serialized_documents() on Worker 0. Please examine the output from the worker processes to identify the problem.

### ISSUE THREAD

**Issue by rahul1g2** [richardpaulhudson/holmes-extractor#10]
I am running the sample code to see the serialized_document format.

Loading Book 1 ‘The Philosopher's Stone’ Ch 1 ‘THE BOY WHO LIVED’.hdc
Book 1 ‘The Philosopher's Stone’ Ch 1 ‘THE BOY WHO LIVED’

**{"Book 1 ‘The Philosopher's Stone’ Ch 1 ‘THE BOY WHO LIVED’": 'tly normal, thank you very much. They were the last people you\xe2\x80\x99d expect to be involved in anything strange or mysterious, because they just didn\xe2\x80\x99t hold with such nonsense. Mr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache.'}**

Not sure what's wrong . Can you please recommend the format on how to pass large text file to effectively load the data

**Comment by richardpaulhudson** [comment]
There should be more error output further up (from Worker 0): could you post it please?

**Comment by richardpaulhudson** [comment]
Closing owing to lack of activity.
